name: Deploy ke CPanel via FTP

on:
  push:
    branches:
      - main # Sesuaikan dengan branch utama repository kamu

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Deploy ke CPanel via FTP
        uses: SamKirkland/FTP-Deploy-Action@4.3.0
        with:
          server: ftpupload.net # Ganti dengan FTP server kamu
          username: ${{ secrets.FTP_USERNAME }} # Simpan username di GitHub Secrets
          password: ${{ secrets.FTP_PASSWORD }} # Simpan password di GitHub Secrets
          local-dir: ./ # Folder yang akan di-upload, bisa sesuaikan
          server-dir: ./syahkty.web.id/htdocs/ # Direktori tujuan di server CPanel
